// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXlVSH61t58Lofi86s7-GOka28lk6GDx8',
    appId: '1:394081490289:web:35ea15af547b9bbc5712d0',
    messagingSenderId: '394081490289',
    projectId: 'fnotes-1adee',
    authDomain: 'fnotes-1adee.firebaseapp.com',
    storageBucket: 'fnotes-1adee.appspot.com',
    measurementId: 'G-GYTBNP207E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKTB4rIpbPq-j33Ivmb24jMP82gZgkosc',
    appId: '1:394081490289:android:a08854507a9158ca5712d0',
    messagingSenderId: '394081490289',
    projectId: 'fnotes-1adee',
    storageBucket: 'fnotes-1adee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbhpZBWJ06OJt6c00MVx4fjSIaE9d6_aM',
    appId: '1:394081490289:ios:3009d9d9ec2bc14a5712d0',
    messagingSenderId: '394081490289',
    projectId: 'fnotes-1adee',
    storageBucket: 'fnotes-1adee.appspot.com',
    iosClientId: '394081490289-fgp3h142giqnhu62i45faif7dr3hc7bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbhpZBWJ06OJt6c00MVx4fjSIaE9d6_aM',
    appId: '1:394081490289:ios:3009d9d9ec2bc14a5712d0',
    messagingSenderId: '394081490289',
    projectId: 'fnotes-1adee',
    storageBucket: 'fnotes-1adee.appspot.com',
    iosClientId: '394081490289-fgp3h142giqnhu62i45faif7dr3hc7bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fnotes',
  );
}
